--
-- Script was generated by Devart dbForge Studio for MySQL, Version 9.2.105.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 7/3/2025 12:45:11 PM
-- Server version: 8.0.38
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS group05db;

CREATE DATABASE group05db
CHARACTER SET utf8mb4
COLLATE utf8mb4_0900_ai_ci;

--
-- Set default database
--
USE group05db;

--
-- Create table `tblproducts`
--
CREATE TABLE tblproducts (
  ProductID int NOT NULL AUTO_INCREMENT,
  ProductName varchar(50) NOT NULL,
  QTY int NOT NULL,
  Price decimal(15, 2) NOT NULL,
  Amount decimal(15, 2) DEFAULT (`QTY` * `Price`),
  Desciption text DEFAULT NULL,
  Created_at datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ProductID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 17,
AVG_ROW_LENGTH = 1489,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create check constraint
--
ALTER TABLE tblproducts
ADD CONSTRAINT tblproducts_chk_1 CHECK (`Price` > 0);

--
-- Create index `ProductName` on table `tblproducts`
--
ALTER TABLE tblproducts
ADD UNIQUE INDEX ProductName (ProductName);

DELIMITER $$

--
-- Create procedure `PRO_INSERETPRODUCT`
--
CREATE
DEFINER = 'villa'@'localhost'
PROCEDURE PRO_INSERETPRODUCT (P_PRODUCTNAME varchar(255),
P_QTY int,
P_PRICE decimal(15, 2),
P_DESCRIPTION text)
BEGIN
  INSERT INTO TblProducts (ProductName, QTY, Price, Desciption)
    VALUE (P_PRODUCTNAME, P_QTY, P_PRICE, P_DESCRIPTION);
END
$$

--
-- Create procedure `PRO_GETPRODUCTBYNAME`
--
CREATE
DEFINER = 'villa'@'localhost'
PROCEDURE PRO_GETPRODUCTBYNAME (P_PRODUCTNAME varchar(255))
BEGIN
  SELECT
    LPAD(ProductID, 3, 0) AS "PRODUCT ID",
    ProductName AS "PRODUCT Name",
    QTY,
    CONCAT('$', FORMAT(Price, 2)) AS "PRICE",
    CONCAT('$', FORMAT(Amount, 2)) AS "AMOUNT_USD",
    CONCAT(FORMAT(Amount * 4100, 0), '៛') AS "AMOUNT_REIL",
    UCASE(Desciption) AS "DISCRIPTION",
    DATE_FORMAT(Created_at, '%d-%M-%y %r') AS "CREATED_AT"
  FROM TblProducts
  WHERE ProductName LIKE CONCAT('%', P_PRODUCTNAME, '%');
END
$$

--
-- Create procedure `PRO_GETPRODUCTBYID`
--
CREATE
DEFINER = 'villa'@'localhost'
PROCEDURE PRO_GETPRODUCTBYID (P_PRODUCTID int)
BEGIN
  SELECT
    LPAD(ProductID, 3, 0) AS "PRODUCT ID",
    ProductName AS "PRODUCT Name",
    QTY,
    CONCAT('$', FORMAT(Price, 2)) AS "PRICE",
    CONCAT('$', FORMAT(Amount, 2)) AS "AMOUNT_USD",
    CONCAT(FORMAT(Amount * 4100, 0), '៛') AS "AMOUNT_REIL",
    UCASE(Desciption) AS "DISCRIPTION",
    DATE_FORMAT(Created_at, '%d-%M-%y %r') AS "CREATED_AT"
  FROM TblProducts
  WHERE ProductID = P_PRODUCTID;
END
$$

DELIMITER ;

--
-- Create view `view_list_product`
--
CREATE
DEFINER = 'villa'@'localhost'
VIEW view_list_product
AS
SELECT
  LPAD(`tblproducts`.`ProductID`, 3, 0) AS `PRODUCT ID`,
  `tblproducts`.`ProductName` AS `PRODUCT Name`,
  `tblproducts`.`QTY` AS `QTY`,
  CONCAT('$', FORMAT(`tblproducts`.`Price`, 2)) AS `PRICE`,
  CONCAT('$', FORMAT(`tblproducts`.`Amount`, 2)) AS `AMOUNT_USD`,
  CONCAT(FORMAT((`tblproducts`.`Amount` * 4100), 0), '៛') AS `AMOUNT_REIL`,
  UPPER(`tblproducts`.`Desciption`) AS `DISCRIPTION`,
  DATE_FORMAT(`tblproducts`.`Created_at`, '%d-%M-%y %r') AS `CREATED_AT`
FROM `tblproducts`;

-- 
-- Dumping data for table tblproducts
--
INSERT INTO tblproducts VALUES
(1, 'Coca', 2, 4.00, 8.00, '', '2025-06-21 01:58:07'),
(3, 'Pepsi', 2, 4.00, 8.00, 'Pepsi', '2025-06-21 02:44:07'),
(4, 'Sting', 1, 1.00, 1.00, 'Sting', '2025-06-21 13:30:04'),
(5, 'Drink', 1, 1.00, 1.00, 'Sting', '2025-06-21 13:31:24'),
(7, 'beer', 12, 1.00, 12.00, 'any beer', '2025-06-21 20:32:47'),
(8, 'Coffe', 1, 0.75, 0.75, 'any coffee', '2025-06-21 20:49:33'),
(9, 'car', 1, 10000.00, 10000.00, 'any car', '2025-06-22 06:34:56'),
(10, 'bus', 1, 10000.00, 10000.00, 'any bus', '2025-06-22 06:41:06'),
(11, 'Van', 2, 5000.00, 10000.00, 'any van ', '2025-06-22 06:44:26'),
(15, 'iphone 11', 1, 400.00, 400.00, 'iphone 11', '2025-07-03 11:26:46'),
(16, 'iphone 12', 12, 600.00, 7200.00, 'iphone 12', '2025-07-03 11:57:47');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;